import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ROFH - Info for CAS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Navbar />

      <main>
        <section className={styles.heroBox}>
          <div className={`${styles["heroCard"]} ${"card"}`}>
            <img className={styles.heroLogo} src="/img/logo.jpg"></img>
            <h1>For CAS</h1>
            <div className={`${"row"} ${styles["heroBtnRow"]}`}>
            
              <div className={`${"col-sm"} ${styles["heroBtnContainer"]}`}>
                <button className={`${"btn btn-primary"}  ${styles["heroBtn"]}`}>Contact Us</button>
              </div>

            </div>
          </div>
        </section>

        {/* ABOUT REACHNINGOUT*/}
        <section className={`${styles["aboutUs"]} ${"container"}`}>
        
        <div className={` ${styles["aboutTopCard"]}`}>
             <div className={`${styles["ourPhilosophyCopy"]}`}>
              <h1>Current Bedlist</h1>
                <p>Reachingout Family Homes is available for placement of children 24 hours a day, 7 days a week. Please contact us during regular business hours at 1-905-837-2098 or after hours on our pager at 1-416-346-2071. A member of our team will be available to speak to you directly about an appropriate placement.</p>
                <p>Reachingout has beds available throughout Southern Ontario including Lindsay, Oshawa, Pickering, Scarborough, Brampton and Brantford.</p>
            </div>
          </div>
          <div className={`${styles["aboutFosteringSection"]}`}>
          
        
         

        
          
        
        
          
            <div className={` ${styles["ourPhilosophy"]} ${styles["aboutCard2"]}`}>
            <div className={styles.ourPhilosophyCopy}>
            <h1>Our Role in Wokring With Agencies</h1>
                <p>We visit our foster homes at least every two weeks to provide optimum support for the children within our care.  We offer foster parents immediate support for any situation they may encounter and regular support at any and all meetings as needed.  We act as a liason for the CAS worker to ensure that the needs of the child are being met to their satisfaction and all Ministry requirements are being met.</p>
                <p>RFH provides regular documentation including 7 day, 30 day and regular POC and medication tracking.  All of our files are reviewed annually by the MCSS and we comply with all Ministry requirements.</p>
            </div>
            </div>
            <div className={`${styles["ourPhilosophy"]} ${styles["aboutCard1"]}`}>

            <div className={styles.ourPhilosophyCopy}>

              <h1>ReachingOut Family Homes is actively recruiting new and skilled homes.</h1>
              <h3>While the site is updated weekly, please contact our agency to inquire about spacing as there may be openings not yet reflected on this page</h3>

            </div>
            </div>
          </div>
         
        </section>

     

        <section id="contact">
         <div className={`${"container"} ${styles["contactContainer"]}`}>

         

              <form action="https://formspree.io/f/mnqrpoqk" method="POST"  className={`${"card"} ${styles["contactCopy"]}`}>
                <h1>Contact Us</h1>
             
                <div className="row">
                    <div className="col-sm-6">
                      <div className="form-group"><label className="form-label">Email Address *</label><input required name="email" placeholder="Email" type="email" className="form-control" /><small className="text-muted form-text">We will never share your email with anyone else.</small></div>
                    </div>
                    <div className="col-sm-6">
                      <div className="form-group"><label className="form-label">Phone *</label><input required name="name" placeholder="Name" type="tel" className="form-control" /></div>
                    </div>
                </div>
                <div className="form-group"><label className="form-label">Message *</label><textarea required name="message" rows="3" id="exampleForm.ControlTextarea1" className="form-control"></textarea></div>
                <button type="submit" className="btn btn-primary">Submit</button><input type="hidden" name="_template" value="box" />
              </form>
              </div>
        </section>      
             
      </main>

      <Footer/>
    </div>
  )
}



